name: Auto Merge Dev to QA

on:
  push:
    branches:
      - dev  # Trigger when code is pushed to dev branch

jobs:
  merge_to_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for merging

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      
      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Shivesh1996/flask_deploment.git

      - name: Remove .env file before merging
        run: |
          git checkout dev
          git rm --cached .env || echo ".env not tracked, skipping..."
          git commit -m "Remove .env from tracking" || echo "No changes to commit"
          
      - name: Merge Dev into QA
        run: |
          git checkout QA
          git merge origin/dev --no-edit
          git push origin QA
